buildscript {
    ext {
        grailsVersion = project.grailsVersion
    }
    repositories {
        mavenLocal()
        maven {
            url "https://repo.grails.org/grails/core"
        }
    }
    dependencies {
        classpath "org.grails:grails-gradle-plugin:$grailsVersion"
    }
}

plugins {
    id 'groovy'
    id 'maven-publish'
    id 'eclipse'
    id 'idea'
    id "org.grails.grails-plugin" version "$grailsVersion"
}

// TODO version...
version = "4.0.0-SNAPSHOT"
group = "org.grails.plugins"

apply plugin: "org.grails.grails-plugin"
apply plugin: "org.grails.grails-doc"

ext {
    grailsVersion = project.grailsVersion
}

java {
    sourceCompatibility = JavaVersion.toVersion("17")
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = "https://repo.grails.org/grails/core"
    }
}

dependencies {
    implementation "org.grails:grails-core"

    console "org.grails:grails-console"

    implementation 'org.apache.wss4j:wss4j-ws-security-common:2.1.3'
    implementation 'org.apache.cxf:cxf-core:4.1.1'
    implementation 'org.apache.cxf:cxf-tools-wsdlto-core:4.1.1'
    implementation 'org.apache.cxf:cxf-tools-wsdlto-frontend-jaxws:4.1.1'
    implementation 'org.apache.cxf:cxf-tools-wsdlto-databinding-jaxb:4.1.1'
    implementation 'org.apache.cxf:cxf-rt-frontend-jaxws:4.1.1'
    implementation 'org.apache.cxf:cxf-rt-frontend-jaxws:4.1.1'
    implementation 'org.apache.cxf:cxf-rt-frontend-jaxrs:4.1.1'
    implementation 'org.apache.cxf:cxf-rt-frontend-jaxrs:4.1.1'
    implementation 'org.apache.cxf:cxf-rt-transports-http:4.1.1'
    implementation('org.apache.cxf:cxf-rt-ws-security:4.1.1'){
		exclude group: 'net.sf.ehcache', module: 'ehcache'
	}

    testImplementation 'org.grails:grails-testing-support'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

jar {
    exclude 'org/grails/cxf/test/**',
            'net/webservicex/**'
}

publishing {
    publications {
        library(MavenPublication) {
            from components.java
        }
    }
}