buildscript {
    ext {
        grailsVersion = project.grailsVersion
    }
    repositories {
        mavenLocal()
        maven {
            url = "https://repo.grails.org/grails/core"
        }
    }
    dependencies {
        classpath "org.apache.grails:grails-gradle-plugins:$grailsVersion"
    }
}

plugins {
    id 'groovy'
    id 'maven-publish'
    id 'eclipse'
    id 'idea'
    id "com.github.ben-manes.versions" version "$benManesVersion"
}

// TODO version...
version = "4.0.0-SNAPSHOT"
group = "org.grails.plugins"

apply plugin: 'org.apache.grails.gradle.grails-plugin'

ext {
    grailsVersion = project.grailsVersion
}

java {
    sourceCompatibility = JavaVersion.toVersion("17")
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = "https://repo.grails.org/grails/core"
    }
    maven {
        url = "https://repository.jboss.org"
    }
}

dependencies {
    implementation "org.apache.grails:grails-core"

    console "org.apache.grails:grails-console"

    implementation "org.apache.cxf:cxf-core:${cxfVersion}"
    implementation "org.apache.cxf:cxf-tools-wsdlto-core:${cxfVersion}"
    implementation "org.apache.cxf:cxf-tools-wsdlto-frontend-jaxws:${cxfVersion}"
    implementation "org.apache.cxf:cxf-tools-wsdlto-databinding-jaxb:${cxfVersion}"
    implementation "org.apache.cxf:cxf-rt-frontend-jaxws:${cxfVersion}"
    implementation "org.apache.cxf:cxf-rt-frontend-jaxws:${cxfVersion}"
    implementation "org.apache.cxf:cxf-rt-frontend-jaxrs:${cxfVersion}"
    implementation "org.apache.cxf:cxf-rt-frontend-jaxrs:${cxfVersion}"
    implementation "org.apache.cxf:cxf-rt-transports-http:${cxfVersion}"
    implementation "org.apache.cxf:cxf-rt-ws-security:${cxfVersion}"

    testImplementation 'org.apache.grails.testing:grails-testing-support-core'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

jar {
    exclude 'org/grails/cxf/test/**',
            'net/webservicex/**'
}

publishing {
    publications {
        library(MavenPublication) {
            from components.java
        }
    }
}