[[configuration]]
=== Plugin Configuration

Once the plugin is installed, and you have your JAXB objects and CXF client port interface on your classpath
(lib or src), add the following to your project's configuration:

[source,yaml]
----
cxf:
    client:
        [beanName]:
            clientInterface: [package and name of wsdl2java -client generated port interface class]
            serviceEndpointAddress: [url for the service]
            username: [username] # optional - used when secured is true - currently wss4j interceptor
            password: [password] # optional - used when secured is true - currently wss4j interceptor
            securityInterceptor: [text name of custom bean to use] # optional - defaults to wss4j interceptor
            inInterceptors: [list of cxf in interceptors to add to the client] # optional - defaults to []
            outInterceptors: [list of cxf out interceptors to add to the client] # optional - defaults to []
            inFaultInterceptors: [list of cxf in fault interceptors to add to the client] # optional - defaults to []
            outFaultInterceptors: [list of cxf out fault interceptors to add to the client] # optional - defaults to []
            enableDefaultLoggingInterceptors: [turn on or off default in/out logging] # optional - defaults to true
            secured: [true or false] # optional - defaults to false
            connectionTimeout: [milliseconds to wait for connection] # optional - defaults to 60000 (0 waits indefinitely)
            receiveTimeout: [milliseconds to wait to receive a response] # optional - defaults to 30000 (0 waits indefinitely)
            allowChunking: [true or false] # optional - defaults to false
            contentType: [http content type] # optional - defaults to 'text/xml; charset=UTF8'
            connection: [ConnectionType.CLOSE or ConnectionType.KEEP_ALIVE] # optional - defaults to ConnectionType.CLOSE
            httpClientPolicy: [text name of custom bean to use] # optional - defaults to null
            authorizationPolicy: [text name of custom bean to use] # optional - defaults to null
            proxyFactoryBindingId: [binding id uri if required] # optional - defaults to ""
            mtomEnabled: [flag to enable mtom] # optional - defaults to false
            secureSocketProtocol: [socket protocol to use for secure service] # optional - defaults to null
            wsdlServiceName: [set to enable mime type mapping] # optional - defaults to null
            wsdlEndpointName: [may be needed for correct wsdl initialization] # optional - defaults to null
            requestContext: [Setting a Request Context Property on the Client Side] # optional - defaults to [:]
            tlsClientParameters: [conduit settings for secure services] # optional - defaults to [:]

            # wsdl config
            wsdl: [location of the wsdl either locally relative to project home dir or a url] # optional - only used by wsdl2java command
            wsdlArgs: [custom list of args to pass, e.g. ["-autoNameResolution", "-validate"]] # optional - only used by wsdl2java command
            namespace: [package name to use for generated classes] # optional - uses packages from wsdl if not provided
            client: [true or false] # optional - tells wsdl2java to output sample clients, usually not needed - defaults to false
            bindingFile: [Specifies JAXWS or JAXB binding file or XMLBeans context file] # optional
            outputDir: [location to output generated files] # optional - defaults to src/java
----

==== Config used at runtime to invoke the service

[cols="1,4,1"]
|===
|Property |Description |Required

|beanName
|This can be any name you would like, but should be unique. This will be the name of the bean the plugin will
auto wire and that you will refer to the bean from your service/controller/etc.
|*Yes*

|clientInterface
|Package name and object name of the wsdl2java generated port interface.
|*Yes*

|serviceEndpointAddress
|Url of the service to call. Can refer to an environment-specific url, as in the example above.
|*Yes*

|username
|Username to pass along with the request in the WSS4J interceptor when `secured` is true. (default: `""`)
|No

|password
|Password to pass along with the request in the WSS4J interceptor when `secured` is true. (default: `""`)
|No

|securityInterceptor
|Provide a single bean name as a string to wire in as an out interceptor for Apache CXF. If you provide a name
for an interceptor, it is implied that `secured=true`. If you require the default WSS4J interceptor you will not
need to set this property; simply set `secured=true` and the `username`/`password` properties. If you set this
to a value then the `username` and `password` fields will be ignored, as it is expected that you will configure
any required property injection in your `resources.groovy` file. You may also provide your custom security
interceptor via the `outInterceptors` property instead — you would still be required to set `secured=true`. This
is here as a convenience for any existing configured clients that do not wish to switch to the newer
`outInterceptors` property. (default: `""`)
|No

|inInterceptors
|Provide a bean name or list of bean names, in `"name"`, `"name, name"`, or `["name","name"]` format, to wire in
as an in interceptor for Apache CXF. The beans must be configured in `resources.groovy`. (default: `[]`)
|No

|outInterceptors
|Provide a bean name or list of bean names, in `"name"`, `"name, name"`, or `["name","name"]` format, to wire in
as an out interceptor for Apache CXF. The beans must be configured in `resources.groovy`. (default: `[]`)
|No

|inFaultInterceptors
|Provide a bean name or list of bean names, in `"name"`, `"name, name"`, or `["name","name"]` format, to wire in
as an in fault interceptor for Apache CXF. The beans must be configured in `resources.groovy`. (default: `[]`)
|No

|outFaultInterceptors
|Provide a bean name or list of bean names, in `"name"`, `"name, name"`, or `["name","name"]` format, to wire in
as an out fault interceptor for Apache CXF. The beans must be configured in `resources.groovy`. (default: `[]`)
|No

|enableDefaultLoggingInterceptors
|When set to true, default in and out logging interceptors will be added to the service. If you require custom
logging interceptors and wish to turn off the default loggers, set this property to false and provide your own
in/out logging interceptors via `inInterceptors`/`outInterceptors`. You may also simply want to disable CXF
logging (soap messages, etc.) by setting this to false without providing your own interceptors. (default: `true`)
|No

|connectionTimeout
|The amount of time, in milliseconds, that the client will attempt to establish a connection before it times
out. `0` specifies that the client will continue to attempt to open a connection indefinitely.
(default: `30000`)
|No

|receiveTimeout
|The amount of time, in milliseconds, that the client will wait for a response before it times out. `0`
specifies that the client will wait indefinitely. (default: `60000`)
|No

|secured
|If true, sets the CXF client params to use the `username`/`password` values via WSS4J. (default: `false`)
|No

|allowChunking
|If true, sets the HTTPClientPolicy `allowChunking` for the client's proxy to true. (default: `false`)
|No

|contentType
|Allows overriding the content type of the http policy, which defaults to `'text/xml; charset=UTF8'`. You might
want to set this to `"application/soap+xml; charset=UTF-8"`, for example.
|No

|connection
|Allows overriding the connection type of the http policy, which defaults to `ConnectionType.CLOSE`. Can attempt
to reuse connections via `ConnectionType.KEEP_ALIVE`.
|No

|httpClientPolicy
|Instead of using the separate timeout/chunking/etc. values, you can create your own `HTTPClientPolicy` bean in
`resources.groovy` and pass the name of the bean here. *This overrides the `connectionTimeout`, `receiveTimeout`
and `allowChunking` values.* (default: `null`)
|No

|authorizationPolicy
|Name of a bean in `resources.groovy` of type `AuthorizationPolicy` that will be used in the http conduit.
(default: `null`)
|No

|proxyFactoryBindingId
|The URI, or ID, of the message binding for the endpoint to use. For SOAP the binding URI (ID) is specified by
the JAX-WS specification. For other message bindings the URI is the namespace of the WSDL extensions used to
specify the binding. To use SOAP 1.2, set this to `"http://schemas.xmlsoap.org/wsdl/soap12/"`. (default: `""`)
|No

|mtomEnabled
|SOAP Message Transmission Optimization Mechanism (MTOM) specifies an optimized method for sending binary data
as part of a SOAP message. Unlike SOAP with Attachments, MTOM requires the use of XML-binary Optimized Packaging
(XOP) packages for transmitting binary data. Using MTOM to send binary data does not require you to fully define
the MIME Multipart/Related message as part of the SOAP binding. (default: `false`)
|No

|secureSocketProtocol
|The secure socket protocol to use for secure services. This will be set on the CXF http object created for
communication with the service. If unspecified, CXF defaults to `"TLS"` when invoking https service endpoints.
Common values are `"SSL"`, `"TLS"` or `"TLSv1"`. (default: `""`)
|No

|wsdl
|Location of the wsdl, either locally or a url (must be available at runtime). Passed into
`JaxWsProxyFactoryBean`. The WSDL will be loaded to handle things that cannot be captured in Java classes via
wsdl2java (like MIME attachments). Requires defining `wsdlServiceName`. (default: `null`)
|No

|wsdlServiceName
|The QName of the service you will be accessing. Passed into `JaxWsProxyFactoryBean`. Only needed when using
WSDL at run-time to handle things that cannot be captured in Java classes via wsdl2java. (example:
`'{http://my.xml.namespace/}TheNameOfMyWSDLServicePorts'`) (default: `null`)
|No

|wsdlEndpointName
|The QName of the endpoint/port in the WSDL you will be accessing. Passed into `JaxWsProxyFactoryBean`. May be
needed when using WSDL at run-time to handle things that cannot be captured in Java classes via wsdl2java.
(example: `'{http://my.xml.namespace/}TheNameOfMyWSDLServicePort'`) (default: `null`)
|No

|requestContext
|Setting a Request Context Property on the Client Side. (default: `[:]`)
|No

|tlsClientParameters
|Configuration parameters for the secure conduit. (default: `[:]`)
|No
|===

==== Config items used by wsdl2java

[cols="1,4,1"]
|===
|Property |Description |Required

|wsdl
|Location of the wsdl, either locally relative to the project home dir or a url. (default: `""`)
|No

|wsdlArgs
|A custom list of args to pass, separated by space, such as `["-autoNameResolution","-validate"]`. This can also
be a single string value such as `"-autoNameResolution"`, but when using multiple custom params you must specify
each in a list (`["-one val","-two","-three val"]`) due to limitations with ant. (default: `""`)
|No

|namespace
|Specifies package names to use for the generated code. (default: uses the package from the wsdl-provided
schema)
|No

|client
|Tells wsdl2java to output sample clients; usually not needed. (default: `false`)
|No

|bindingFile
|Path of binding file to pass to wsdl2java. (default: `""`)
|No

|outputDir
|Directory to write the generated code into. (default: `"src/java"`)
|No
|===

You simply refer to your client beans from a controller/service/taglib like the following:

[source,groovy]
----
class DemoController {
    SimpleServicePortType simpleServiceClient
    ComplexServicePortType complexServiceClient

    def simpleServiceDemo = {
        SimpleRequest request = new SimpleRequest(age: 100, name: "Bob")
        SimpleResponse response = simpleServiceClient.simpleMethod(request)

        render(view: '/index', model: [simpleRequest: request, simpleResponse: response])
    }
}
----

NOTE: You should type the beans with the CXF port interface type so as to get IDE auto-completion on the
service methods. By simply using `def` you will not know what methods are available on the soap service without
peeking into the wsdl or the generated client port interface manually.
