[[customInterceptors]]
=== Custom In/Out Interceptors

==== In Interceptors

You can wire in your own custom in interceptors by adding the `inInterceptors` property to the configured
client. In this example, custom in logging interceptors are wired in and the default logging interceptors are
disabled by setting `enableDefaultLoggingInterceptors = false`.

In `resources.groovy`, define the bean wiring:

[source,groovy]
----
customLoggingInInterceptor(CustomLoggingInInterceptor) {
    name = "customLoggingInInterceptor"
}

verboseLoggingInInterceptor(VerboseCustomLoggingInInterceptor) {
    name = "verboseLoggingInInterceptor"
}

customLoggingOutInterceptor(CustomLoggingOutInterceptor) {
    name = "customLoggingOutInterceptor"
}
----

In the `cxf.client` config block, define the web service client and provide the interceptor bean name(s):

[source,yaml]
----
cxf:
  client:
      simpleServiceInterceptorClient:
          wsdl: docs/SimpleService.wsdl # only used for wsdl2java script target
          clientInterface: cxf.client.demo.simple.SimpleServicePortType
          serviceEndpointAddress: http://localhost:8080/services/simple
          outInterceptors: customLoggingOutInterceptor # single item, comma separated list, or groovy list
          inInterceptors:
            - customLoggingInInterceptor
            - verboseLoggingInInterceptor
          enableDefaultLoggingInterceptors: false
          namespace: cxf.client.demo.simple
----

Here is the code for `customLoggingInInterceptor` (`verboseLoggingInInterceptor` is almost identical):

[source,groovy]
----
package com.cxf.demo.logging

import org.apache.cxf.common.injection.NoJSR250Annotations
import org.apache.cxf.common.logging.LogUtils
import org.apache.cxf.interceptor.AbstractLoggingInterceptor
import org.apache.cxf.interceptor.Fault
import org.apache.cxf.message.Message
import org.apache.cxf.phase.Phase

import java.util.logging.Logger

@NoJSR250Annotations
public class CustomLoggingInInterceptor extends AbstractLoggingInterceptor {

    private static final Logger LOG = LogUtils.getLogger(CustomLoggingInInterceptor)
    def name

    public CustomLoggingInInterceptor() {
        super(Phase.RECEIVE)
        log LOG, "Creating the custom interceptor bean"
    }

    public void handleMessage(Message message) throws Fault {
        log LOG, "$name :: custom in logger"
    }

    @Override
    protected Logger getLogger() {
        LOG
    }
}
----

NOTE: In your constructor you will need to be mindful of what `Phase` you set your interceptor for. See the docs
at https://cxf.apache.org/docs/interceptors.html[Apache CXF Interceptors].

You will need to set the logging level to enable the logging:

[source,groovy]
----
info 'org.grails.cxf.client'
info 'org.apache.cxf.interceptor'
info 'blah.blah.blah' // whatever package your custom interceptors are in
// debug 'org.apache.cxf.interceptor' // choose the appropriate level
----

==== Out Interceptors

You can wire in your own custom out interceptors by adding the `outInterceptors` property to the configured
client, using the same YAML shape shown above.

Here is the code for `customLoggingOutInterceptor`:

[source,groovy]
----
package com.cxf.demo.logging

import org.apache.cxf.common.injection.NoJSR250Annotations
import org.apache.cxf.common.logging.LogUtils
import org.apache.cxf.interceptor.AbstractLoggingInterceptor
import org.apache.cxf.interceptor.Fault
import org.apache.cxf.message.Message
import org.apache.cxf.phase.Phase

import java.util.logging.Logger

@NoJSR250Annotations
public class CustomLoggingOutInterceptor extends AbstractLoggingInterceptor {

    private static final Logger LOG = LogUtils.getLogger(CustomLoggingOutInterceptor)
    def name

    public CustomLoggingOutInterceptor() {
        super(Phase.WRITE)
        log LOG, "Creating the custom interceptor bean"
    }

    public void handleMessage(Message message) throws Fault {
        log LOG, "$name :: custom out logger"
    }

    @Override
    protected Logger getLogger() {
        LOG
    }
}
----

NOTE: Since the out interceptor is in the `PRE_STREAM` phase (removed in MESSAGE mode), you have to configure
out interceptors to run at the `WRITE` phase instead, as shown above.

==== In Fault / Out Fault Interceptors

You can wire in your own custom in/out fault interceptors by adding the `inFaultInterceptors` or
`outFaultInterceptors` property to the configured client — the wiring follows the same pattern as the in/out
interceptors above.

You will need to set the logging level to enable the logging, as shown above.
