[[secureSocketProtocol]]
=== Setting Secure Socket Protocol

If you would like to set the secure socket protocol for a secure service, you can use the `CxfClientConstants`
class to set the bean property. The types provided are:

[source,groovy]
----
public static final String SSL_PROTOCOL_TLSV1 = 'TLSv1'
public static final String SSL_PROTOCOL_SSLV3 = 'SSLv3'
----

You may also provide configuration via `tlsClientParameters` for the client. Using this you can set any of the
following:

* `disableCNCheck`: boolean
* `sslCacheTimeout`: integer
* `secureSocketProtocol`: e.g. `CxfClientConstants.SSL_PROTOCOL_SSLV3`
* `useHttpsURLConnectionDefaultSslSocketFactory`: boolean
* `useHttpsURLConnectionDefaultHostnameVerifier`: boolean
* `cipherSuitesFilter.exclude`: `List<String>`
* `cipherSuitesFilter.include`: `List<String>`

This is done via the configuration block, for example:

[source,groovy]
----
cxf {
    client {
        simpleServiceClient {
            //...
            tlsClientParameters = [
                disableCNCheck: true,
                sslCacheTimeout: 100,
                secureSocketProtocol: CxfClientConstants.SSL_PROTOCOL_SSLV3,
                cipherSuitesFilter: [
                    include: ['.*_EXPORT_.*', '.*_EXPORT1024_.*'],
                    exclude: ['.*_DH_anon_.*']
                ]
            ]
        }
    }
}
----

Either may be used, but `secureSocketProtocol` takes precedence for setting the protocol. Both
`secureSocketProtocol` and `tlsClientParameters` may be used together, but if you want to set more than just the
protocol it is preferred to use the `tlsClientParameters` map.

Not all features of the http conduit are supported. You can read more about conduit settings at
https://cwiki.apache.org/confluence/display/CXF20DOC/TLS+Configuration[Apache CXF TLS Configuration].
